import Head from 'next/head'
import {Text, Flex, Link, HStack} from '@chakra-ui/react'
import '@fontsource/open-sans'



export default function Home() {
  return (
    <>
      <Head>
        <title>My Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex width={'100%'} height={'100vh'} bg={'secundary.grey1'} direction={'column'}>
        <HStack justifyContent={'space-around'} borderBottom={'2px'} borderColor={'brand.pink3'}>
          <Text color={'secundary.grey3'}>Gabriela Marchiori</Text>
          <HStack>
            <Link href='#home' color={'secundary.grey3'}>Home</Link>
            <Link href='#projects' color={'secundary.grey3'}>Projects</Link>
            <Link href='#contact' color={'secundary.grey3'}>Contact</Link>
            <Link href='#social-media' color={'secundary.grey3'}>Social Media</Link>
            <Link href='#about-me' color={'secundary.grey3'}>About me</Link>
          </HStack>
        </HStack>
        
        <Flex id='about-me'>
          <Text>Deu certo</Text>
        </Flex>
        <Text>Teste</Text>
      </Flex>
      
    </>
  )
}
